# Generated by Django 3.1.9 on 2021-10-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0002_auto_20210916_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('default', 'Default'), ('email_only', 'Email only'), ('none', 'None')], default='default', max_length=15, verbose_name='Action backend'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='language',
            field=models.CharField(choices=[('nl', 'Dutch')], default='nl', max_length=10, verbose_name='form language'),
        ),
    ]
